# Handling Imbalanced Dataset

1.Up Sampling

2.Down Sampling

In [18]:
import numpy as np
import pandas as pd

#set the random seed for reproducibility
np.random.seed(123)

# Create dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples*class_0_ratio)
n_class_1=n_samples-n_class_0

In [19]:
n_class_0,n_class_1

(900, 100)

In [20]:
# Create the dataframe with imbalanced data.

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target':[0]*n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target':[1]*n_class_1
})

In [21]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [22]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [23]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

# Upsampling

In [24]:
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [25]:
from sklearn.utils import resample
df_minority_unsampled=resample(df_minority,replace=True,
                               n_samples=len(df_majority),
                               random_state=42
                               )

In [26]:
df_minority_unsampled.shape

(900, 3)

In [27]:
df_minority_unsampled.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [28]:
df_upsampled=pd.concat([df_majority,df_minority_unsampled])

In [29]:
df_upsampled.shape

(1800, 3)

In [30]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

# Down Sampling

In [31]:
import numpy as np
import pandas as pd

#set the random seed for reproducibility
np.random.seed(123)

# Create dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples*class_0_ratio)
n_class_1=n_samples-n_class_0

In [32]:
n_class_0,n_class_1

(900, 100)

In [33]:
# Create the dataframe with imbalanced data.

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target':[0]*n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target':[1]*n_class_1
})

In [34]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [35]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [36]:
# DownSampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [39]:
from sklearn.utils import resample
df_majority_downsampled=resample(df_majority,replace=False,
                               n_samples=len(df_minority),
                               random_state=42
                               )

In [40]:
df_majority_downsampled.shape

(100, 3)

In [41]:
df_downsampled=pd.concat([df_minority,df_majority_downsampled])

In [42]:
df_downsampled.shape

(200, 3)

In [43]:
df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64